"""
Django settings for stacktrails project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from split_settings import tools


tools.include(
    "config/base.py",
    "config/apps.py",
    "config/db.py",
    "config/cors.py",
    "config/mailconf.py",
    "config/drf.py",
    "config/celery_.py",
    "config/logs.py",
    "config/caches.py",
    "config/others.py",
)
