name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{secrets.DB_NAME}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name:  Create env file
        run: |
          touch ././stacktrails/.env
          echo "dev=true" >> ././stacktrails/.env
          echo "SECRET_KEY=${{secrets.SECRET_KEY}}" >> ././stacktrails/.env
          echo "POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}" >> ././stacktrails/.env
          echo "BROKER_URL=${{secrets.BROKER_URL}}" >> ././stacktrails/.env
          echo "RABBITMQ_DEFAULT_PASS=${{secrets.RABBITMQ_DEFAULT_PASS}}" >> ././stacktrails/.env
          echo  "HOSTNAME=www" >> ././stacktrails/.env
          echo "RABBITMQ_DEFAULT_USER=www" >> ././stacktrails/.env
          echo "RESULT_BACKEND=${{secrets.RESULT_BACKEND}}" >> ././stacktrails/.env
          echo "DB_USER=${{secrets.DB_USER}}" >> ././stacktrails/.env
          echo "DB_PASSWORD=${{secrets.DB_PASSWORD}}" >> ././stacktrails/.env
          echo "DB_HOST=${{secrets.DB_HOST}}" >> ././stacktrails/.env
          echo "DB_NAME=${{secrets.DB_NAME}}" >> ././stacktrails/.env
          echo "REDIS_HOST=${{secrets.REDIS_HOST}}" >> ././stacktrails/.env
          echo "REDIS_PORT=${{secrets.REDIS_PORT}}" >> ././stacktrails/.env
          echo "REDIS_URI=${{secrets.REDIS_URI}}" >> ././stacktrails/.env


      - name: Run docker-compose
        run: |
          docker compose -f ././docker-compose.yml up -d
          docker compose -f ././docker-compose.yml ps

      - name: Test and submit coverage report
        run: |
          docker compose exec app python manage.py test --settings=stacktrails.settings -v 1
          pip install coveralls
          cd stacktrails && coveralls --service=github

      - name: bring down docker-compose
        run: docker compose -f ././docker-compose.yml down
